### ISSUE TITLE
Script roda no Windows?

### ISSUE THREAD

**Issue by MarcoKuntz** [rictom/cnpj-mysql#1]
Estou tendo dificuldade em rodá-lo no windows. Como sou usuário inexperiente de Python, é bem provável que o problema esteja aqui entre a cadeira e o teclado.

Retorno no comando:

File "C:\CNPJ\dados_cnpj_para_mysql.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

Porém, o Script para o Sqlite rodou que foi uma beleza.

C:\CNPJ>python dados_cnpj_para_sqlite.py
descompactando dados-publicos-zip\f.k03200$w.simples.csv.d11009.zip
descompactando dados-publicos-zip\f.k03200$z.d11009.cnaecsv.zip
descompactando dados-publicos-zip\f.k03200$z.d11009.moticsv.zip
descompactando dados-publicos-zip\f.k03200$z.d11009.municcsv.zip

Alguma sugestão?

**Comment by rictom** [comment]
Pelo texto que você colocou não saberia dizer. Vc rodou o script em um console do windows? Usou o comando 
>python dados_cnpj_para_mysql.py
? Se vc colar o comando que vc colocou no console ajudaria a debugar. 
Vc está rodando um servidor mysql localmente? Tem usuário e senha? Criou a base de dados cnpj? 
Vc editou alguma coisa no script? Isso porque a linha 7 só tem três aspas.

**Comment by MarcoKuntz** [comment]
Rapaz, sabe a história de time que está ganhando?

Rersolvi minha vida com o Sqlite, e toca o barco. Quando tiver um tempinho sobrando vou ver qual a lambança que arrumei com o script.

Obrigado pela atenção e parabéns pelo código. No meu note, um i7 de 7ª geração levou pouco mais de 2h pra executar tudo.

Abraço.
