### ISSUE TITLE
Campo data_exclusao_mei com data futura na tabela 'simples'

### ISSUE THREAD

**Issue by jhon100** [rictom/cnpj-mysql#2]
Olá, notei que alguns registros na tabela do simples (já na última versão publicada) tem o campo opcao_simples = 'S' e, ao mesmo tempo, o campo data_exclusao_mei preenchido com uma data futura como '20221231'. 
Acontece, por exemplo, nos cnpj_basico = 01422623, 03679703, 06147233

Tem também com data recente como cnpj_basico = 05578155, 05753186 e data_exclusao_mei = '20220930'

Precisaria saber se a empresa é MEI, aparentemente checar apenas se opcao_simples = 'S' não é suficiente, considerando estas datas...
Sabe se isso faz sentido ou se é um erro de dados da Receita?

Obrigados e parabéns pelo script.

**Comment by rictom** [comment]
Creio que a adesão ao simples e a empresa ser enquadrada em MEI são coisas distintas, mas seria bom uma opinião de alguém da área...
Meu palpite é que a empresa ultrapassou o limite de faturamento e por isso se programa para sair do MEI... Eu conferi com uma tabela do ano passado, nessas duas primeiras empresas estava com o campo data_exclusao_mei vazias (o que também não ajuda muito...). Infelizmente consultando direto no site da receita não aparece informação sobre o enquadramento MEI. 
Que bom que o script está sendo útil.

**Comment by jhon100** [comment]
Desculpe, me confundi na hora de digitar. Eu queria ter dito que o campo **opcao_mei** está marcado como 'S'. 
Mas pela sua resposta creio que já entendi, rodei uma consulta aqui pra ver se achava algum registro com **opcao_mei** = 'S' e **data_exclusao_mei** anterior a este ano e não retornou nada, ou seja, quando opcao_mei = 'S' e data_exclusao_mei está preenchido, só está preenchido com data futura, o que corrobora sua tese. Obrigado.
