### ISSUE TITLE
Erro na linha 355 do dados_cnpj_mysql.py

### ISSUE THREAD

**Issue by andre-webdesigner** [rictom/cnpj-mysql#3]
`Exception has occurred: IndexError
list index out of range
  File "F:\webdesign\cnpj-mysql-main\dados_cnpj_mysql.py", line 355, in carregaTabelaCodigo
    arquivo = list(glob.glob(os.path.join(pasta_saida, '*' + extensaoArquivo)))[0]
  File "F:\webdesign\cnpj-mysql-main\dados_cnpj_mysql.py", line 362, in <module>
    carregaTabelaCodigo('.CNAECSV','cnae')`

Esse é o erro que está dando ao tentar executar o script PY
Já instalei todas as bibliotecas, instalei o python na mesma versão recomendada, criei a tabela e também conferi todos os arquivos na pasta dados-publicos-zip.. Poderia me ajudar com isso?

**Comment by rictom** [comment]
Todos os arquivos do site da Receita devem estar na pasta dados-publicos-zip, que serão descompactados pelo script e colocados na pasta dados-publicos. Parece que o script não achou o F.K03200$Z.D21217.CNAECSV, que compactado tem o nome de Cnaes.zip. Vc baixou esse arquivo?

**Comment by andre-webdesigner** [comment]
Olá, sim baixei!
No total, são 37 arquivos dentro da pasta (incluindo o Cnaes.zip)

**Comment by rictom** [comment]
O script conseguiu descompactar os zips? na pasta dados-publicos apareceu um arquivo .CNAECSV?

**Comment by andre-webdesigner** [comment]
Não, na pasta dados-publicos não tem nenhum dos arquivos descompactados

Apenas os arquivos compactados na pasta dados-publicos-zip

**Comment by rictom** [comment]
Qual o exato comando para vc rodar o script? Se vc rodou em um console de DOS, deve ter aparecido algum log. O console estava na pasta onde está o script? Isso é importante porque os caminhos das pastas  dados-publicos-zip e  dados-publicos (se vc deixou do jeito que está no script) são relativas ao "path" no console. Por exemplo, vc tem que deixar o console apontando para esta pasta F:\webdesign\cnpj-mysql-main... Então vc tem fazer os comandos no console, F: <enter>, depois cd F:\webdesign\cnpj-mysql-main. Daí vc roda o script com o comando python dados_cnpj_mysql.py

**Comment by andre-webdesigner** [comment]
Pode ter sido isso! 

Porque meu windows fica no disco C:/ e os arquivos estão no disco F:/ (porque eu não tinha espaço no SSD)
Tentei rodar ele pelo terminal e também pelo vscode (Porém, ambos estão instalados no C:/)

Vou tentar liberar espaço no disco C:/ que é mais garantido que funcione com os arquivos lá e volto pra falar se o problema foi solucionado

**Comment by rictom** [comment]
Vc pode rodar pelo F: mesmo, é só alterar as linhas no script para
pasta_compactados = r"F:\webdesign\cnpj-mysql-main\dados-publicos-zip"
pasta_saida = r"F:\webdesign\cnpj-mysql-main\dados-publicos"

**Comment by andre-webdesigner** [comment]
> Vc pode rodar pelo F: mesmo, é só alterar as linhas no script para pasta_compactados = r"F:\webdesign\cnpj-mysql-main\dados-publicos-zip" pasta_saida = r"F:\webdesign\cnpj-mysql-main\dados-publicos"

Deu certíssimo agora! Coloquei pra descompactar (Ta rodando pelo vscode)
Depois deixa um link aí para doações de quem quer colaborar com seu projeto

**Comment by rictom** [comment]
Legal. Depois posta aqui se deu certo até o final e quanto tempo levou, que eu não costumo usar esse script, eu uso a base de cnpj em sqlite.

**Comment by andre-webdesigner** [comment]
Não consegui acompanhar ao certo quanto tempo levou, mas uma média de 5 horas com CPU i5 e 8gb de RAM

**Comment by rictom** [comment]
Valeu. É bom saber que o script está funcionando.

**Comment by fabioselau077** [comment]
> Não consegui acompanhar ao certo quanto tempo levou, mas uma média de 5 horas com CPU i5 e 8gb de RAM

Amigo, deu quantos GB no banco depois de finalizar?
