### ISSUE TITLE
Não consigo executar o código

### ISSUE THREAD

**Issue by ndr3wpss** [rictom/cnpj-mysql#4]
Olá, tudo bem?
Já baixei todas os arquivos compactados disponibilizados  pelo link, ao todo tenho 37 pastas compactadas na pasta dados-publicos-zip. Porém ao abrir o console do anaconda e executar o código: ' python dados_cnpj_lista_url.py' , tenho como retorno essa resposta:
python: can't open file 'C:\Users\andrew.santos_freteb\dados_cnpj_lista_url.py': [Errno 2] No such file or directory.

Poderia me ajudar? PS: já criei o banco de dados cnpj no mysql e também a pasta dados-publicos.

Valeuu!

**Comment by rictom** [comment]
Boa tarde,

O script dados_cnpj_lista_url.py serve só para listar os arquivos na página de download da receita. Se vc já baixou todos os arquivos, não precisa disso (mas não entendi o erro que apareceu)

Supondo que o mysql esteja funcionando, vc deve alterar as linhas 20 do dados_cnpj_mysql.py com os parâmetros do seu servidor
#%% DEFINA os parâmetros do servidor.
tipo_banco= 'mysql'
dbname = 'cnpj'
username = 'root'
password = ''
host = '127.0.0.1'

Para criar a base em mysql, o comando é
python dados_cnpj_mysql.py

**Comment by ndr3wpss** [comment]
Onde posso encontrar o dados_cnpj_mysql.py?

**Comment by rictom** [comment]
Vc tem que baixar o código primeiro, tem o botão verde "Code" e selecione "Download ZIP". Daí vc descompacta, as pastas dados-publicos-zip e dados-publicos tem que estar no mesmo diretório que o dados_cnpj_mysql.py.
