### ISSUE TITLE
Travando no "carregando: arq="

### ISSUE THREAD

**Issue by fabioselau077** [rictom/cnpj-mysql#5]
Sempre quando chega nessa etapa do script apenas salva o log "carregando: arq=" mas não passa para o próximo print que é "lendo csv", é normal isso?
Antes disso utilizei o dados_cnpj_baixa.py para baixar os arquivos .zip

<img width="519" alt="image" src="https://github.com/rictom/cnpj-mysql/assets/57275833/3cabc165-8728-49ba-89bb-646bd22bb0a3">

Tô enviando para um RDS Postgre utilizando uma EC2 com 32GB de RAM.

Pelo que olhei sempre é nesse mesmo arquivo, já tem quase 1 hora que tá nesse arquivo de 300mb. o que eu estranhei é que apenas deu print na linha de cima, na linha de baixo não deu, mas não tem nenhuma função entre essas duas linhas

**Comment by rictom** [comment]
Não sei te dizer o motivo. Desculpe, não faço idéia do que seja RDS EC2... 
Eu imagino que em postgres vai precisar de uns 100GB de disco só pra base.
Vc pode tentar isolar o problema, fazendo o seguinte... 
Lá na pasta dados-publicos-zip e deixe só só o Estabelecimentos3.zip (mova pra outro lugar os estabelecimentos0.zip e os outros). Para ver se a rotina inteira funciona, também remova os empresas0,zip a empresas8.zip (deixe só o empresas9.zip).
Vc vai ter que apagar as tabelas no postgres e executar a rotina de novo. Como o script não checa a quantidade de zips, daí vc consegue ver na hora se ele está travando especificamente no Estabelecimentos3.zip, então talvez esse arquivo esteja com problema e você tenta baixar esse zip de novo.

**Comment by fabioselau077** [comment]
> 

São produtos da AWS (Amazon), RDS é o banco de dados postgres e o EC2 é uma máquina virtual, pra não ter que ficar executando no meu local.
Acredito que ainda está em processamento, pois no banco de dados estou verificando que tá aumentando o tamanho das tabelas, especialmente da tabela empresas, vou ver se faço uma melhoria, criar uma tabela chamada "migrations", que ao iniciar armazena os nomes dos arquivos e o status (pendente, finalizado), dai em qualquer momento vc pode pausar e depois retornar de onde parou sem ter problemas, vou ver se consigo aqui e faço a PR
<img width="493" alt="image" src="https://github.com/rictom/cnpj-mysql/assets/57275833/232b9452-af9f-46fd-b8cd-4364afae058b">

**Comment by rictom** [comment]
Se você estivesse trabalhando localmente, eu faria uma sugestão de rodar o projeto cnpj-sqlite, que gera o db sqlite em menos de 2 horas e depois usar algum aplicativo como o DBeaver para carregar do sqlite pro postgres. Eu li algum lugar que era bem rápido, mas nunca testei.

**Comment by fabioselau077** [comment]
> Se você estivesse trabalhando localmente, eu faria uma sugestão de rodar o projeto cnpj-sqlite, que gera o db sqlite em menos de 2 horas e depois usar algum aplicativo como o DBeaver para carregar do sqlite pro postgres. Eu li algum lugar que era bem rápido, mas nunca testei.

Vou tentar essa opção tbm, tava pensando em criar uma máquina no EC2 e salvar o sqlite lá também, depois criar um backend básico (laravel ou nodejs) que só retorna os dados do sqlite, vai servir somente como consulta mesmo.

Somente o custo de armazenamento de 150GB da AWS RDS é $40 por mês (apenas o armazenamento), talve compensa mais fazer isso mesmo de sqlite.
Você tem mais ou menos o tamanho do sqlite final?

Obrigado

**Comment by rictom** [comment]
Com índices em algumas colunas, fica 30GB em sqlite. Sem indíces fica um pouco menor.

**Comment by fabioselau077** [comment]
> Com índices em algumas colunas, fica 30GB em sqlite. Sem indíces fica um pouco menor.

Eu abandonei em enviar direto para o Postgres, fiz da seguinte maneira:
-> Gerei o sqlite com o cnpj-sqlite e armazenei no local
-> Criei um EC2 com 32Gb de RAM e um banco de dados (RDS) Postgres com 4GB de RAM e 2 CPU (acho que seria o mínimo)
-> Enviei o sqlite para o EC2 (se eu n tivesse gerado no local, compensava eu ter gerado no ec2 direto o sqlite) - ficou em torno de 30GB
-> No EC2 Ubuntu eu utilizei o pgloader para enviar do sqlite para o Postgres, demorou cerca de 1 hora e meia (somente o vacuum no final durou 20 minutos)
-> Comparei o total (count) das tabelas com o sqlite no local e bateu todas as quantidades de rows, foi criado os índices também pelo pgloader automaticamente
-> Encerrei a EC2 pq n irei mais utilizar (caso preferir dá pra usar o pgloader no local direto)
-> Reduzi o tamanho do banco para 2Gb de RAM e 2 CPU (evitar gastos)

<img width="516" alt="image" src="https://github.com/rictom/cnpj-mysql/assets/57275833/f9dd622b-2ad8-411d-84b1-b56131c49f0d">

Obrigado pelos pacotes, ajudaram muito!

**Comment by rictom** [comment]
Legal. Da próxima vez, se for criar o sqlite direto no EC2, me fala quanto tempo leva. É bom saber pra fazer um comparativo de tempo de execução.

**Comment by fabioselau077** [comment]
> Legal. Da próxima vez, se for criar o sqlite direto no EC2, me fala quanto tempo leva. É bom saber pra fazer um comparativo de tempo de execução.

Em breve vou fazer novamente e te informo os tempos médios.

Outra coisa, dataset da Receita é atualizado 1x por mês, como sites como casadosdados possuem os CNPJ's criados todos os dias? Tu tem ideia?

**Comment by rictom** [comment]
O Serpro tem uma api paga para baixar os dados de cnpjs. Talvez esses sites usem isso, selecionando só os cnpjs novos, mas é só um palpite.

**Comment by fabioselau077** [comment]
> O Serpro tem uma api paga para baixar os dados de cnpjs. Talvez esses sites usem isso, selecionando só os cnpjs novos, mas é só um palpite.

É cara, pelo q vi só o Serpro, mas é pago e pra eles n iriam compensar pagar... Tô achando que eles possuem acesso com alguma esquema, funcionário público de alto cargo, órgão que faz parte do SISP... Algum esquema tem kkkk

Mesmo q for pelo Serpro, lá vc n recupera lista de cnp's, vc n consegue filtrar por exemplo: "Quero todos os cnp's criados ontem", vc literalmente consegue só recuperar dados de um CNPJ, cnpj q vc tem q saber...

**Comment by Juuhz** [comment]
> Outra coisa, dataset da Receita é atualizado 1x por mês, como sites como casadosdados possuem os CNPJ's criados todos os dias? Tu tem ideia?

Meus amigos, achei interessante esse tópico e estou em busca dessa respostas. Os senhores sabem como a casadosdados possuem os dados atualizados diariamente?

**Comment by brunomarlan** [comment]
sim, eles sequenciam utilizando cnpj base. a partir do ultimo criado , fazem multirequisicoes e quando cnpj eh existente ele considera como aberto hoje. nada de api. eu mesmo fiz aqui um checker com o codigo de sequenciamento inteligente.
