### ISSUE TITLE
Possibilidade de filtrar carregamento

### ISSUE THREAD

**Issue by jonasnaves** [rictom/cnpj-mysql#8]
Tem como filtrar o carregamento para importar ao banco de dados apenas empresas que eu quero tipo:
Filtrar estado, apenas empresas ativas, apenas empresas mei, apenas empresas que possuem telefone ou outras opções de filltro.

Acho que isso iria deixar mais rapido o processo

**Comment by rictom** [comment]
Isso é possível, mas acho que ficaria bem mais prático vc carregar a base em sqlite, que leva muito menos tempo que em mysql e depois filtrar o que vc precisa. O projeto https://github.com/rictom/cnpj-sqlite gera a base em sqlite e leva em torno de 2 horas.
